sudo: false
language: php
php:
  - nightly
  - 7.0
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
